apiVersion: v2
name: argo-workflow
description: Argo Workflows + ingress + workflow templates
type: application
version: 0.1.0

dependencies:
- name: argo-workflows
  version: "0.40.8"
  repository: "https://argoproj.github.io/argo-helm"
