image:
  repository: prom/prometheus
  tag: v2.51.0

namespace: monitoring
replicaCount: 1
retention: "7d"
scrapeInterval: "15s"
evaluationInterval: "15s"

ingress:
  host: prometheus.local

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "500m"

storage:
  enabled: false
  size: "5Gi"
  storageClass: "local-path"