apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: '0.40.8'
    chart: argo-workflows
    helm:
      values: |
        server:
          secure: false
          authModes:
            - server
          extraArgs:
            - --auth-mode=server
            - --secure=false
          serviceType: ClusterIP
          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true