# Dev overrides — only what differs from values.yaml
image:
  tag: be4b6e8

replicaCount: 1

hpa:
  minReplicas: 1
  maxReplicas: 3

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "200m"
